# Generated by Django 6.0.2 on 2026-03-23 18:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_remove_profile_workouts_per_week_profile_carbs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
